services:
  rustapp:
    container_name: rustapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL = postgres://postgres:postgres@dbrust:5432/postgres
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = postgres
    depends_on:
      - dbrust
  dbrust:
    container_name: dbrust
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}